version: '3.8'

services:
  web:
    image: caddy:2
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      # - $PWD/Caddyfile:/etc/caddy/Caddyfile
      - $PWD:/usr/share/caddy
      - caddy_data:/data
      - caddy_config:/config

volumes:
  caddy_data:
    external: true
  caddy_config:
