name: Update README cards

on:
  schedule:
    - cron: "21 0 * * *" # Runs once daily at 21 minute past midnight
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v6

      - name: Generate top languages card
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: top-langs
          options: username=${{ github.repository_owner }}&layout=compact&langs_count=6
          path: profile/top-langs.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Check for changes
        id: check_changes
        run: |
          git diff --quiet profile/*.svg || echo "has_changes=true" >> $GITHUB_OUTPUT

      - name: Commit cards
        if: steps.check_changes.outputs.has_changes == 'true'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add profile/*.svg
          git commit -m "chore: update stats cards"
          git push
